# Generated by Django 2.0.6 on 2018-06-18 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicaconsulta',
            options={'managed': True},
        ),
    ]
