# Generated by Django 2.0.6 on 2018-06-18 02:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20180618_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaconsulta',
            name='gradder',
            field=models.IntegerField(choices=[(0, 2), (1, 1.75), (2, 1.5), (3, 1.25), (4, 1.0), (5, 0.75), (6, 0.5), (7, 0.25), (8, 0)], db_column='GRADDER', default=8),
        ),
        migrations.AddField(
            model_name='clinicaconsulta',
            name='gradizq',
            field=models.IntegerField(choices=[(0, 2), (1, 1.75), (2, 1.5), (3, 1.25), (4, 1.0), (5, 0.75), (6, 0.5), (7, 0.25), (8, 0)], db_column='GRADIZQ', default=8),
        ),
        migrations.AlterField(
            model_name='clinicaconsulta',
            name='coddoctor',
            field=models.ForeignKey(blank=True, db_column='CODDOCTOR', null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ClinicaOftalmologo'),
        ),
        migrations.AlterField(
            model_name='clinicaconsulta',
            name='codpaciente',
            field=models.ForeignKey(blank=True, db_column='CODPACIENTE', null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.ClinicaPaciente'),
        ),
        migrations.AlterField(
            model_name='clinicaconsulta',
            name='enfermedad',
            field=models.CharField(choices=[('Astigmatismo', 'Astigmatismo'), ('Miopia', 'Miopia'), ('Ninguna', 'Ninguna')], db_column='ENFERMEDAD', default=3, max_length=100),
        ),
        migrations.AlterField(
            model_name='clinicaconsulta',
            name='fechaconsulta',
            field=models.DateField(db_column='FECHACONSULTA', default=datetime.date(2018, 6, 18)),
        ),
        migrations.AlterField(
            model_name='clinicaconsulta',
            name='numconsulta',
            field=models.IntegerField(db_column='NUMCONSULTA', primary_key=True, serialize=False),
        ),
    ]
